[symbol]
prefix = "CUSTOM"
description = "USD_JPY_DAILY_FIXED"
ticker = "USD_JPY_DAILY_FIXED"
currency = "JPY"
basecurrency = "USD"
period = "1D"
type = "forex"
mintick = 0.01000000
pricescale = 100
minmove = 1
pointvalue = 1.00000000
timezone = "UTC"
volumetype = "base"
#avg_spread =
#taker_fee =
#maker_fee =
#target_price_average =
#target_price_high =
#target_price_low =
#target_price_date =

# Opening hours
[[opening_hours]]
day = 1
start = "00:00:00"
end = "23:59:59"

[[opening_hours]]
day = 2
start = "00:00:00"
end = "23:59:59"

[[opening_hours]]
day = 3
start = "00:00:00"
end = "23:59:59"

[[opening_hours]]
day = 4
start = "00:00:00"
end = "23:59:59"

[[opening_hours]]
day = 7
start = "00:00:00"
end = "23:59:59"

# Session starts
[[session_starts]]
day = 1
time = "00:00:00"

# Session ends
[[session_ends]]
day = 7
time = "23:59:59"
